version: '3.9'

services:
  postgres:
    image: postgres:16.0
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/public
    environment:
      - POSTGRES_PASSWORD=user
      - POSTGRES_USER=user
      - POSTGRES_DB=postgres